project:
  type: website

website:
  title: "Makarand Nadendla, Causality God"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/makarandnadendla
      - icon: twitter
        href: https://twitter.com/TheChosenMach
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

